### PR TITLE
Fix for duplicated imports

### PR DESCRIPTION
**Pull request by ZeroX-DG**
I think I fixed the duplicated imports problem and I also added a new test for that.

### CODE REVIEW

**Comment by simeg** [comment]
Referencing #13.

**Comment by simeg** [comment]
Hi @ZeroX-DG.

A lot of things are happening in this PR, and I'm not sure if you're waiting for me to do something or if you're in the process of doing something. Let me know if you need my help.

**Comment by ZeroX-DG** [comment]
Hi @simeg ,
I've fixed the duplicated import bug and added a new feature called "write install script to package.json" so basically this feature will ask the user if they want to write their script to a txt file (install_dependencies.txt) or to the package.json file so that they can just run "npm run setup" to install all the dependencies. And I also fixed the "undefined IMAGE_SOURCE and IMAGE_DEST variable"

**Comment by ZeroX-DG** [comment]
So now it's on you to decide :)

**Comment by simeg** [comment]
The tests are not passing so I cannot merge this even if I wanted to.

**Comment by simeg** [comment]
@ZeroX-DG I appreciated you adding a new feature, but this PR is too messy to merge.

First of all, it's not passing the CI process. The tests are saying invalid node version. I'm not sure if this is because of your changes or some dependency problem. What would be useful is if you split this PR into 1 or 2 PRs - one for the initial fix (fix duplicate imports) and one for the new feature you added. That way it's much easier to grasp the implications of the changes.

Thanks.

**Pull request closed without merging**
