### PR TITLE
Feature write install script to package.json

### PR DESCRIPTION
**Pull request by ZeroX-DG**
Hey @simeg,
This is a PR for the "write install script to package.json" feature :)

### CODE REVIEW

**Comment by simeg** [comment]
Hi @ZeroX-DG. Thanks, the code looks good.

However you need to rebase on top of master for me to be able to merge this, let me know if you need assistance!

**Comment by ZeroX-DG** [comment]
Ok, I'll work on it, thanks for merging. I'm still new to git so I'm sorry for all the troubles and mistakes that I made :)

**Comment by ZeroX-DG** [comment]
Hey @simeg , I've rebased on to of master (I think so), if this is not what you mean then please tell me what to do :) thank you :)

**Comment by simeg** [comment]
Hi @ZeroX-DG.

No worries, this part about git is confusing. The problem is that some code in master is conflicting with the code in this PR (two different changes in the same place) and it cannot be merged without conflicts, so we have to resolve the conflicts before this PR can become mergable.

You have instructions here on GitHub how to resolve this using a merge commit, where you resolve all the conflicts with a merge commit.

**Here's a picture of the steps, just click `command line instructions` to show them:**
image

In the second step (`git pull ...`) git will make you resolve all conflicts before continuing, just follow the steps that git provide you with and make sure you keep the code that you want to put in master.

Let me know if you need any more assistance :)

**Comment by simeg** [comment]
Closing due to #17.

**Pull request closed without merging**
